server:
  port: ":8080"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "0923"
  name: "mygoproject"

mq:
  url: "amqp://guest:guest@localhost:5672/"
  brokers:
    - "localhost:9092"
  group_id: "email-classifier-group"

jwt:
  secret: "zwy923"

redis:
  addr: "localhost:6379"
  password: "0923"
  db: 0
